### ISSUE TITLE
Slayerify 'Good Band'

### ISSUE THREAD

**Issue by ryandudek** [ghostmechanics/ghostbot#11]
Plz do the needful

**Comment by johnmichel** [comment]
@ryandudek 

![](http://bukk.it/soon2.jpg)

![](https://s3.amazonaws.com/f.cl.ly/items/2O1k0Z3T2G3i1v0i3R2E/Screen%20Shot%202015-05-13%20at%202.22.35%20PM.png)

**Comment by ryandudek** [comment]
LLOL @ 'The Suburbs'
